import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "@/contexts/context";

const myFont = localFont({
  src: [
    {
      path: "/../../public/Poppins/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    // {
    //   path: "/../../../public/Poppins/Poppins-Bold.ttf",
    //   weight: "600",
    //   style: "normal",
    // },
  ],
});

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
      className={myFont.className}
      >
        <AppProvider>
        {children}
        </AppProvider>
      </body>
    </html>
  );
}
